# Generated by Django 3.1 on 2020-08-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batsmen_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Runs', models.IntegerField()),
                ('Avg', models.FloatField()),
                ('Rank', models.IntegerField()),
                ('Played', models.IntegerField()),
                ('Strike_rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'Batsmen_Info',
                'verbose_name_plural': 'Batsmen_Infos',
            },
        ),
    ]
