# Generated by Django 3.1 on 2020-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('USN', models.CharField(max_length=50)),
                ('AGE', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('GENDER', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
            ],
            options={
                'verbose_name': 'student_details',
                'verbose_name_plural': 'student_detailss',
            },
        ),
    ]
